### Get all movies
GET http://localhost:1234/movies

### Get one film by id (404 expected)
GET http://localhost:1234/movies/1

### Get one film by id (200 expexted)
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### GET all movies for an specific genre (404 expected)
GET http://localhost:1234/movies?genre=terror

### GET all movies for an specific genre (200 expected)
GET http://localhost:1234/movies?genre=action

### POST Create a movie  (400 expected)
POST http://localhost:1234/movies
Content-type : application/json

{
//    "id": "6a360a18-c645-4b47-9a7b-2a71babbf3e0",
    "title": "The Emoji Movie",
    "year": 1017,
    "director": "Tony Leondis",
    "duration": -86,
    "poster": "https://m.media-amazon.com/images/I/81KdmiQh+jL._SX342_.jpg",
    "genre": [
      "terror"
    ],
    "rate": 3.4
  }
  
### POST Create a movie (with sql not part of the object. Expected igonre the field)
POST http://localhost:1234/movies
Content-type : application/json

{
  "sql": "Delete from users",
//    "id": "6a360a18-c645-4b47-9a7b-2a71babbf3e0",
    "title": "The Emoji Movie",
    "year": 2017,
    "director": "Tony Leondis",
    "duration": 86,
    "poster": "https://m.media-amazon.com/images/I/81KdmiQh+jL._SX342_.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Fantasy",
      "Comedy"
    ],
    "rate": 3.4
  }

### POST Create a movie
POST http://localhost:1234/movies
Content-type : application/json

{
//    "id": "6a360a18-c645-4b47-9a7b-2a71babbf3e0",
    "title": "The Emoji Movie",
    "year": 2017,
    "director": "Tony Leondis",
    "duration": 86,
    "poster": "https://m.media-amazon.com/images/I/81KdmiQh+jL._SX342_.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Fantasy",
      "Comedy"
    ],
    "rate": 3.4
  }

### UPDATE a part of the movie (PATCH)
PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-type : application/json

{
    "id": 123,
    "year": 2017
}

